#############################################################
#
#   .o88b.  .d88b.  .d8888. .88b  d88.  .d88b.  .d8888.
#  d8P  Y8 .8P  Y8. 88'  YP 88'YbdP`88 .8P  Y8. 88'  YP
#  8P      88    88 `8bo.   88  88  88 88    88 `8bo.
#  8b      88    88   `Y8b. 88  88  88 88    88   `Y8b.
#  Y8b  d8 `8b  d8' db   8D 88  88  88 `8b  d8' db   8D
#   `Y88P'  `Y88P'  `8888Y' YP  YP  YP  `Y88P'  `8888Y'
# 
# ★ StarLab RPL - COSMOS GROUND STATION ★
# Communications and Observation Station for Mission Operations and Surveillance
#
# By Martin Ortiz
# Version 1.0.0
# Date 06.08.2023
#
#############################################################
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/desing_files\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1150, 650)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 550))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("/* Global Styling */\n"
"QMainWindow {\n"
"  background-color: #111217;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #111217;\n"
"  color: #b3b8c2;\n"
"  selection-color: #ffffff;\n"
"  selection-background-color: #6357a3;\n"
"}\n"
"\n"
"/* ToolTip Styling */\n"
"QToolTip {\n"
"  background-color: #0a0c10;\n"
"  font: 500 9pt \"Video Med\";\n"
"  color: #ffffff;\n"
"  border-right: 3px solid #6c5fb4;\n"
"  border-radius: 3px;\n"
"}\n"
"#label_loadingDots {\n"
"  font: 63 68pt \"Video SemBd\";\n"
"}\n"
"\n"
"/** Status Bar**/\n"
"#statusBarFrame QFrame {\n"
"  margin-top: 1px;\n"
"  font: 600 8pt \"Video SemBd\";\n"
"  background-color: rgba(0, 0, 0, 0);\n"
"  border: 0;\n"
"  color: rgb(73, 78, 89);\n"
"}\n"
"\n"
"/* Sidebar Buttons */\n"
"#frame_topSideBarButtons QPushButton {\n"
"  font: 500 8pt \"Video Med\";\n"
"  border-radius: 4px;\n"
"  border: 1px solid #2b2d30;\n"
"  color: #808183;\n"
"}\n"
"#frame_topSideBarButtons QPushButton:hover {\n"
"  background-color: #1a1b1f;\n"
"}\n"
"#frame_topSideBarButtons QPushButton:pressed {\n"
"  background-color: #2b2d30;\n"
"}\n"
"#frame_topSideBarButtons QPushButton:checked {\n"
"  color: #ffffff;\n"
"  border: 1px solid #6357a4;\n"
"  background-color: #1b1a28;\n"
"}\n"
"#frame_topSideBarButtons QPushButton:disabled {\n"
"  border: 1px solid #1e1f22;\n"
"  color: #292b29;\n"
"  background-color: #17191d;\n"
"}\n"
"\n"
"#frame_mainControls QPushButton,\n"
"#frame_terminalContainer QPushButton,\n"
"#frame_connectionDropDown QPushButton {\n"
"  font: 500 8pt \"Video Med\";\n"
"  border-radius: 4px;\n"
"  border: 1px solid #2b2d30;\n"
"  color: #808183;\n"
"}\n"
"#frame_mainControls QPushButton:hover,\n"
"#frame_terminalContainer QPushButton:hover,\n"
"#frame_connectionDropDown QPushButton:hover {\n"
"  background-color: #1a1b1f;\n"
"}\n"
"#frame_mainControls QPushButton:pressed,\n"
"#frame_terminalContainer QPushButton:pressed,\n"
"#frame_connectionDropDown QPushButton:pressed {\n"
"  background-color: #2b2d30;\n"
"}\n"
"\n"
"#frame_connectionDropDown QPushButton:checked {\n"
"  color: #ffffff;\n"
"  border: 1px solid #6357a4;\n"
"  background-color: #1b1a28;\n"
"}\n"
"\n"
"#frame_connectionDropDown QPushButton:disabled {\n"
"  border: 1px solid #1e1f22;\n"
"  color: #292b29;\n"
"  background-color: #17191d;\n"
"}\n"
"\n"
"/* preferences page */\n"
"#frame_preferencesSideBar QPushButton {\n"
"  font: 500 8pt \"Video Med\";\n"
"  border-radius: 4px;\n"
"  border: 1px solid #2b2d30;\n"
"  color: #808183;\n"
"}\n"
"#frame_preferencesSideBar QPushButton:hover {\n"
"  background-color: #1a1b1f;\n"
"}\n"
"#frame_preferencesSideBar QPushButton:pressed {\n"
"  background-color: #2b2d30;\n"
"}\n"
"#frame_preferencesSideBar QPushButton:checked {\n"
"  color: #ffffff;\n"
"  border: 1px solid #6357a4;\n"
"  background-color: #1b1a28;\n"
"}\n"
"#frame_preferencesSideBar QPushButton:disabled {\n"
"  border: 1px solid #292a30;\n"
"  color: #292b29;\n"
"  background-color: #12141a;\n"
"}\n"
"\n"
"/*  STATE AND COUNTDONW  LABEL // BTN */\n"
"#frame_StateAndCountdownContainer QLabel {\n"
"  border-radius: 4px;\n"
"  font: 600 10.5pt \"Video SemBd\";\n"
"  border: 1px solid #45484e;\n"
"  background-color: #212227;\n"
"}\n"
"#frame_StateAndCountdownContainer QPushButton {\n"
"  border-radius: 4px;\n"
"  font: 600 10.5pt \"Video SemBd\";\n"
"  border: 1px solid #45484e;\n"
"  background-color: #212227;\n"
"}\n"
"#frame_StateAndCountdownContainer QPushButton:hover {\n"
"  background-color: #37383d;\n"
"}\n"
"\n"
"/*  TLM CONTAINERS */\n"
"#frame_mainTlmLabels QFrame {\n"
"  border-radius: 4px;\n"
"  border: 1px solid #45484e;\n"
"  background-color: #212227;\n"
"  font: 63 9pt \"Video Cond SemBd\";\n"
"}\n"
"#frame_secondaryAndButtonContainer QFrame {\n"
"  border-radius: 4px;\n"
"  border: 1px solid #45484e;\n"
"  background-color: #212227;\n"
"  font: 63 9pt \"Video Cond SemBd\";\n"
"}\n"
"\n"
"#frame_mainTlmLabels QLabel {\n"
"      \n"
"    font: 63 9pt \"Video Cond SemBd\";\n"
"    border: none;\n"
"    background-color: none;\n"
"}\n"
"\n"
"#frame_BigTlmLabels QLabel {\n"
"      font: 63 10pt \"Video Cond SemBd\";\n"
"    border: none;\n"
"    background-color: none;\n"
"}\n"
"\n"
"#frame_secondaryAndButtonContainer QLabel {\n"
"  font: 600 9pt \"Video SemBd\";\n"
"    border: none;\n"
"    background-color: none;\n"
"}\n"
"\n"
"/** DROP COMBO BOX **/\n"
"#frame_connectionDropDown QComboBox {\n"
"  font: 500 8pt \"Video Med\";\n"
"  padding-left: 5px;\n"
"  border-radius: 4px;\n"
"  color: #808183;\n"
"  border: 1px solid #2b2d30;\n"
"}\n"
"\n"
"#frame_connectionDropDown QComboBox:hover {\n"
"  background-color: #1a1b1f;\n"
"}\n"
"\n"
"#frame_connectionDropDown QComboBox:drop-down {\n"
"  border: 0px;\n"
"}\n"
"\n"
"\n"
"#frame_connectionDropDown QComboBox::down-arrow {\n"
"    image: url(:/icons/icons/down_arrow.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"#frame_connectionDropDown QComboBox QAbstractItem {\n"
"  padding: 4px 8px;\n"
"  border-radius: 4px;\n"
"  selection-background-color: none;\n"
"  border: none;\n"
"}\n"
"#frame_connectionDropDown QComboBox QAbstractItem::item {\n"
"  padding: 4px 8px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"#frame_connectionDropDown QComboBox QAbstractItemView::item:selected {\n"
"  border: none;\n"
"  background-color: #6357a4;\n"
"}\n"
"\n"
"#frame_connectionDropDown QListView {\n"
"  border-radius: 4px;\n"
"  border: 1px solid #2b2d30;\n"
"  background-color: #12141a;\n"
"  outline: none;\n"
"}\n"
"\n"
"/* WINDOW CONTROL BUTTONS */\n"
"#frame_mainControls QPushButton:checked {\n"
"  border-bottom: 2px solid #6357a3;\n"
"  border-left: 2px solid rgba(108, 95, 180, 228);\n"
"  background-color: rgba(32, 34, 38, 155);\n"
"}\n"
"\n"
"/* TERMINAL */\n"
"/* message sender */\n"
"#frame_MessageSender,\n"
"#frame_graphContainer,\n"
"#frame_terminalContainer {\n"
"  border-radius: 4px;\n"
"  border: 1px solid #373a3e;\n"
"}\n"
"/* TEXT BROWSER */\n"
"#textBrowser_terminal {\n"
"  padding-left: 4px;\n"
"  color: #808183;\n"
"  text-align: left;\n"
"  font: 500 10pt \"Video Med\";\n"
"  selection-color: #ffffff;\n"
"  selection-background-color: #6357a3;\n"
"  border: none;\n"
"}\n"
"#frame_terminalTextBrowserContainer {\n"
"  border-radius: 4px;\n"
"  border: 1px solid #373a3e;\n"
"}\n"
"\n"
"/* LINE EDIT */\n"
"#frame_MessageSender QLineEdit {\n"
"  background-color: transparent;\n"
"  border: none;\n"
"  padding-left: 4px;\n"
"  padding-right: 15px;\n"
"  font: 500 9pt \"Video Med\";\n"
"  color: #737476;\n"
"  padding-bottom: 2px;\n"
"  selection-color: #ffffff;\n"
"  selection-background-color: #6357a3;\n"
"}\n"
"#frame_MessageSender QLineEdit:focus {\n"
"  color: #808183;\n"
"}\n"
"\n"
"/*SCROLLBAR*/\n"
"QScrollBar {\n"
"  margin: 3px 0px 3px 3px;\n"
"  border: 0;\n"
"  border-radius: 4px;\n"
"  width: 15px;\n"
"}\n"
"QScrollBar::handle::vertical {\n"
"  border-radius: 3px;\n"
"  background-color: #282a2e;\n"
"  min-height: 20px;\n"
"}\n"
"QScrollBar::handle::vertical:hover {\n"
"  border-radius: 3px;\n"
"  background-color: #535558;\n"
"  min-height: 20px;\n"
"}\n"
"QScrollBar::sub-line {\n"
"  border: none;\n"
"  height: 0;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"  border: none;\n"
"  height: 0;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"  border: none;\n"
"  height: 0;\n"
"}\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"  background: none;\n"
"}\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"#label_longVersion {\n"
"  border-radius: 4px;\n"
"  font: 600 9.5pt \"Video SemBd\";\n"
"    color: #808183;\n"
"\n"
"}\n"
"#frame_preferencesContainer QLabel {\n"
"    font: 63 11pt \"Video SemBd\";\n"
"}\n"
"\n"
"/* SEPARATOR LINES */\n"
"#line,\n"
"#line_1,\n"
"#line_2,\n"
"#line_3,\n"
"#line_4,\n"
"#line_5,\n"
"#line_6,\n"
"#line_7,\n"
"#line_8,\n"
"#line_9,\n"
"#line_10 {\n"
"  border: 0;\n"
"  background-color: #45484e;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(4, 0, 4, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topbarseparator = QtWidgets.QFrame(self.centralwidget)
        self.topbarseparator.setMinimumSize(QtCore.QSize(0, 34))
        self.topbarseparator.setMaximumSize(QtCore.QSize(16777215, 34))
        self.topbarseparator.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topbarseparator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbarseparator.setObjectName("topbarseparator")
        self.verticalLayout.addWidget(self.topbarseparator)
        self.centralFrame = QtWidgets.QFrame(self.centralwidget)
        self.centralFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.centralFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centralFrame.setLineWidth(0)
        self.centralFrame.setObjectName("centralFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralFrame)
        self.verticalLayout_2.setContentsMargins(4, 0, 4, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget_central = QtWidgets.QStackedWidget(self.centralFrame)
        self.stackedWidget_central.setLineWidth(0)
        self.stackedWidget_central.setObjectName("stackedWidget_central")
        self.page_preferences = QtWidgets.QWidget()
        self.page_preferences.setObjectName("page_preferences")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_preferences)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_preferencesSideBar = QtWidgets.QFrame(self.page_preferences)
        self.frame_preferencesSideBar.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_preferencesSideBar.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_preferencesSideBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_preferencesSideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_preferencesSideBar.setObjectName("frame_preferencesSideBar")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_preferencesSideBar)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 4)
        self.verticalLayout_16.setSpacing(4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.btn_goBackHome = QtWidgets.QPushButton(self.frame_preferencesSideBar)
        self.btn_goBackHome.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_goBackHome.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_goBackHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_goBackHome.setObjectName("btn_goBackHome")
        self.verticalLayout_16.addWidget(self.btn_goBackHome)
        self.line_8 = QtWidgets.QFrame(self.frame_preferencesSideBar)
        self.line_8.setMinimumSize(QtCore.QSize(0, 1))
        self.line_8.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_16.addWidget(self.line_8)
        spacerItem = QtWidgets.QSpacerItem(20, 438, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem)
        self.line_6 = QtWidgets.QFrame(self.frame_preferencesSideBar)
        self.line_6.setMinimumSize(QtCore.QSize(0, 1))
        self.line_6.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_16.addWidget(self.line_6)
        self.btn_reloadWIndow = QtWidgets.QPushButton(self.frame_preferencesSideBar)
        self.btn_reloadWIndow.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_reloadWIndow.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_reloadWIndow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_reloadWIndow.setObjectName("btn_reloadWIndow")
        self.verticalLayout_16.addWidget(self.btn_reloadWIndow)
        self.btn_launchRoomPanel = QtWidgets.QPushButton(self.frame_preferencesSideBar)
        self.btn_launchRoomPanel.setEnabled(False)
        self.btn_launchRoomPanel.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_launchRoomPanel.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_launchRoomPanel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_launchRoomPanel.setObjectName("btn_launchRoomPanel")
        self.verticalLayout_16.addWidget(self.btn_launchRoomPanel)
        self.btn_openDashboardEditor = QtWidgets.QPushButton(self.frame_preferencesSideBar)
        self.btn_openDashboardEditor.setEnabled(False)
        self.btn_openDashboardEditor.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_openDashboardEditor.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_openDashboardEditor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_openDashboardEditor.setObjectName("btn_openDashboardEditor")
        self.verticalLayout_16.addWidget(self.btn_openDashboardEditor)
        self.horizontalLayout_8.addWidget(self.frame_preferencesSideBar)
        self.frame_preferencesContainer = QtWidgets.QFrame(self.page_preferences)
        self.frame_preferencesContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_preferencesContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_preferencesContainer.setObjectName("frame_preferencesContainer")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_preferencesContainer)
        self.verticalLayout_17.setContentsMargins(65, 0, 85, 4)
        self.verticalLayout_17.setSpacing(4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_longVersion = QtWidgets.QLabel(self.frame_preferencesContainer)
        self.label_longVersion.setMinimumSize(QtCore.QSize(0, 32))
        self.label_longVersion.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_longVersion.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_longVersion.setObjectName("label_longVersion")
        self.verticalLayout_17.addWidget(self.label_longVersion)
        self.line_7 = QtWidgets.QFrame(self.frame_preferencesContainer)
        self.line_7.setMinimumSize(QtCore.QSize(0, 1))
        self.line_7.setMaximumSize(QtCore.QSize(116888, 1))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_17.addWidget(self.line_7)
        self.scrollArea_SettingContainer = QtWidgets.QScrollArea(self.frame_preferencesContainer)
        self.scrollArea_SettingContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_SettingContainer.setLineWidth(0)
        self.scrollArea_SettingContainer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_SettingContainer.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_SettingContainer.setWidgetResizable(True)
        self.scrollArea_SettingContainer.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.scrollArea_SettingContainer.setObjectName("scrollArea_SettingContainer")
        self.scrollAreaWidgetContents_settings = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_settings.setGeometry(QtCore.QRect(0, 0, 730, 554))
        self.scrollAreaWidgetContents_settings.setObjectName("scrollAreaWidgetContents_settings")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_settings)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_preferencesLAyoutContainer = QtWidgets.QFrame(self.scrollAreaWidgetContents_settings)
        self.frame_preferencesLAyoutContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_preferencesLAyoutContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_preferencesLAyoutContainer.setObjectName("frame_preferencesLAyoutContainer")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_preferencesLAyoutContainer)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.layout_preferences = QtWidgets.QVBoxLayout()
        self.layout_preferences.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_preferences.setSpacing(7)
        self.layout_preferences.setObjectName("layout_preferences")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_preferences.addItem(spacerItem1)
        self.verticalLayout_22.addLayout(self.layout_preferences)
        self.verticalLayout_21.addWidget(self.frame_preferencesLAyoutContainer)
        self.scrollArea_SettingContainer.setWidget(self.scrollAreaWidgetContents_settings)
        self.verticalLayout_17.addWidget(self.scrollArea_SettingContainer)
        self.horizontalLayout_8.addWidget(self.frame_preferencesContainer)
        self.stackedWidget_central.addWidget(self.page_preferences)
        self.page_centralDashboard = QtWidgets.QWidget()
        self.page_centralDashboard.setObjectName("page_centralDashboard")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_centralDashboard)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_LeftSideBar = QtWidgets.QFrame(self.page_centralDashboard)
        self.frame_LeftSideBar.setMinimumSize(QtCore.QSize(260, 0))
        self.frame_LeftSideBar.setMaximumSize(QtCore.QSize(260, 16777215))
        self.frame_LeftSideBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_LeftSideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_LeftSideBar.setLineWidth(1)
        self.frame_LeftSideBar.setObjectName("frame_LeftSideBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_LeftSideBar)
        self.verticalLayout_3.setContentsMargins(0, 0, 4, 0)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_topSideBarButtons = QtWidgets.QFrame(self.frame_LeftSideBar)
        self.frame_topSideBarButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_topSideBarButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_topSideBarButtons.setObjectName("frame_topSideBarButtons")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_topSideBarButtons)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame = QtWidgets.QFrame(self.frame_topSideBarButtons)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_missionDisplay = QtWidgets.QPushButton(self.frame)
        self.btn_missionDisplay.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_missionDisplay.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_missionDisplay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_missionDisplay.setObjectName("btn_missionDisplay")
        self.horizontalLayout_7.addWidget(self.btn_missionDisplay)
        self.verticalLayout_12.addWidget(self.frame)
        self.frame_recordingButtons = QtWidgets.QFrame(self.frame_topSideBarButtons)
        self.frame_recordingButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_recordingButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_recordingButtons.setObjectName("frame_recordingButtons")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_recordingButtons)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_toggleRecordings = QtWidgets.QPushButton(self.frame_recordingButtons)
        self.btn_toggleRecordings.setMinimumSize(QtCore.QSize(11, 32))
        self.btn_toggleRecordings.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_toggleRecordings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/logs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_toggleRecordings.setIcon(icon)
        self.btn_toggleRecordings.setCheckable(True)
        self.btn_toggleRecordings.setChecked(False)
        self.btn_toggleRecordings.setObjectName("btn_toggleRecordings")
        self.horizontalLayout_5.addWidget(self.btn_toggleRecordings)
        self.btn_toggleCloudBackup = QtWidgets.QPushButton(self.frame_recordingButtons)
        self.btn_toggleCloudBackup.setEnabled(False)
        self.btn_toggleCloudBackup.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_toggleCloudBackup.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_toggleCloudBackup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cloud.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_toggleCloudBackup.setIcon(icon1)
        self.btn_toggleCloudBackup.setCheckable(True)
        self.btn_toggleCloudBackup.setObjectName("btn_toggleCloudBackup")
        self.horizontalLayout_5.addWidget(self.btn_toggleCloudBackup)
        self.verticalLayout_12.addWidget(self.frame_recordingButtons)
        self.verticalLayout_3.addWidget(self.frame_topSideBarButtons)
        self.line_5 = QtWidgets.QFrame(self.frame_LeftSideBar)
        self.line_5.setMinimumSize(QtCore.QSize(0, 1))
        self.line_5.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.frame_StateAndCountdownContainer = QtWidgets.QFrame(self.frame_LeftSideBar)
        self.frame_StateAndCountdownContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_StateAndCountdownContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_StateAndCountdownContainer.setObjectName("frame_StateAndCountdownContainer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_StateAndCountdownContainer)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_state = QtWidgets.QLabel(self.frame_StateAndCountdownContainer)
        self.label_state.setMinimumSize(QtCore.QSize(0, 39))
        self.label_state.setMaximumSize(QtCore.QSize(16777215, 39))
        self.label_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state.setObjectName("label_state")
        self.verticalLayout_11.addWidget(self.label_state)
        self.label_countdown = QtWidgets.QLabel(self.frame_StateAndCountdownContainer)
        self.label_countdown.setMinimumSize(QtCore.QSize(0, 27))
        self.label_countdown.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_countdown.setAlignment(QtCore.Qt.AlignCenter)
        self.label_countdown.setObjectName("label_countdown")
        self.verticalLayout_11.addWidget(self.label_countdown)
        self.verticalLayout_3.addWidget(self.frame_StateAndCountdownContainer)
        self.line_4 = QtWidgets.QFrame(self.frame_LeftSideBar)
        self.line_4.setMinimumSize(QtCore.QSize(0, 1))
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.frame_mainTlmLabels = QtWidgets.QFrame(self.frame_LeftSideBar)
        self.frame_mainTlmLabels.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_mainTlmLabels.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mainTlmLabels.setObjectName("frame_mainTlmLabels")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_mainTlmLabels)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_BigTlmLabels = QtWidgets.QFrame(self.frame_mainTlmLabels)
        self.frame_BigTlmLabels.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_BigTlmLabels.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_BigTlmLabels.setObjectName("frame_BigTlmLabels")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_BigTlmLabels)
        self.verticalLayout_10.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.layout_BigTlmLabels = QtWidgets.QGridLayout()
        self.layout_BigTlmLabels.setSpacing(0)
        self.layout_BigTlmLabels.setObjectName("layout_BigTlmLabels")
        self.verticalLayout_10.addLayout(self.layout_BigTlmLabels)
        self.verticalLayout_8.addWidget(self.frame_BigTlmLabels)
        self.frame_PrimaryTlmLabels = QtWidgets.QFrame(self.frame_mainTlmLabels)
        self.frame_PrimaryTlmLabels.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_PrimaryTlmLabels.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_PrimaryTlmLabels.setObjectName("frame_PrimaryTlmLabels")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_PrimaryTlmLabels)
        self.verticalLayout_9.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.layout_PrimaryTlmLabel = QtWidgets.QGridLayout()
        self.layout_PrimaryTlmLabel.setSpacing(0)
        self.layout_PrimaryTlmLabel.setObjectName("layout_PrimaryTlmLabel")
        self.verticalLayout_9.addLayout(self.layout_PrimaryTlmLabel)
        self.verticalLayout_8.addWidget(self.frame_PrimaryTlmLabels)
        self.verticalLayout_3.addWidget(self.frame_mainTlmLabels)
        self.line_3 = QtWidgets.QFrame(self.frame_LeftSideBar)
        self.line_3.setMinimumSize(QtCore.QSize(0, 1))
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.scrollArea_SideBar = QtWidgets.QScrollArea(self.frame_LeftSideBar)
        self.scrollArea_SideBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_SideBar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_SideBar.setWidgetResizable(True)
        self.scrollArea_SideBar.setObjectName("scrollArea_SideBar")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 256, 283))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_secondaryAndButtonContainer = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_secondaryAndButtonContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_secondaryAndButtonContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_secondaryAndButtonContainer.setObjectName("frame_secondaryAndButtonContainer")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_secondaryAndButtonContainer)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(4)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_SecondaryTlmLabel = QtWidgets.QFrame(self.frame_secondaryAndButtonContainer)
        self.frame_SecondaryTlmLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_SecondaryTlmLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SecondaryTlmLabel.setObjectName("frame_SecondaryTlmLabel")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_SecondaryTlmLabel)
        self.verticalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layout_SecondaryTlmLabelContainer = QtWidgets.QGridLayout()
        self.layout_SecondaryTlmLabelContainer.setSpacing(0)
        self.layout_SecondaryTlmLabelContainer.setObjectName("layout_SecondaryTlmLabelContainer")
        self.verticalLayout_5.addLayout(self.layout_SecondaryTlmLabelContainer)
        self.verticalLayout_18.addWidget(self.frame_SecondaryTlmLabel)
        self.frame_CommandButton = QtWidgets.QFrame(self.frame_secondaryAndButtonContainer)
        self.frame_CommandButton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_CommandButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CommandButton.setObjectName("frame_CommandButton")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_CommandButton)
        self.verticalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.layout_buttonContainer = QtWidgets.QGridLayout()
        self.layout_buttonContainer.setSpacing(4)
        self.layout_buttonContainer.setObjectName("layout_buttonContainer")
        self.verticalLayout_6.addLayout(self.layout_buttonContainer)
        self.verticalLayout_18.addWidget(self.frame_CommandButton)
        self.verticalLayout_7.addWidget(self.frame_secondaryAndButtonContainer)
        spacerItem2 = QtWidgets.QSpacerItem(20, 152, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.scrollArea_SideBar.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea_SideBar)
        self.frame_connectionDropDown = QtWidgets.QFrame(self.frame_LeftSideBar)
        self.frame_connectionDropDown.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_connectionDropDown.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_connectionDropDown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_connectionDropDown.setLineWidth(0)
        self.frame_connectionDropDown.setObjectName("frame_connectionDropDown")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_connectionDropDown)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_2 = QtWidgets.QFrame(self.frame_connectionDropDown)
        self.line_2.setMinimumSize(QtCore.QSize(0, 1))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.frame_connectionOptions = QtWidgets.QFrame(self.frame_connectionDropDown)
        self.frame_connectionOptions.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_connectionOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_connectionOptions.setObjectName("frame_connectionOptions")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_connectionOptions)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cb_bauds = QtWidgets.QComboBox(self.frame_connectionOptions)
        self.cb_bauds.setMinimumSize(QtCore.QSize(72, 27))
        self.cb_bauds.setMaximumSize(QtCore.QSize(1000, 27))
        self.cb_bauds.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_bauds.setObjectName("cb_bauds")
        self.horizontalLayout_4.addWidget(self.cb_bauds)
        self.cb_ports = QtWidgets.QComboBox(self.frame_connectionOptions)
        self.cb_ports.setMinimumSize(QtCore.QSize(72, 27))
        self.cb_ports.setMaximumSize(QtCore.QSize(1000, 27))
        self.cb_ports.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_ports.setObjectName("cb_ports")
        self.horizontalLayout_4.addWidget(self.cb_ports)
        self.btn_toggleAutoReconnection = QtWidgets.QPushButton(self.frame_connectionOptions)
        self.btn_toggleAutoReconnection.setMinimumSize(QtCore.QSize(47, 27))
        self.btn_toggleAutoReconnection.setMaximumSize(QtCore.QSize(47, 27))
        self.btn_toggleAutoReconnection.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_toggleAutoReconnection.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/plug_volt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_toggleAutoReconnection.setIcon(icon2)
        self.btn_toggleAutoReconnection.setIconSize(QtCore.QSize(14, 14))
        self.btn_toggleAutoReconnection.setCheckable(True)
        self.btn_toggleAutoReconnection.setChecked(False)
        self.btn_toggleAutoReconnection.setObjectName("btn_toggleAutoReconnection")
        self.horizontalLayout_4.addWidget(self.btn_toggleAutoReconnection)
        self.verticalLayout_4.addWidget(self.frame_connectionOptions)
        self.btn_connectBtn = QtWidgets.QPushButton(self.frame_connectionDropDown)
        self.btn_connectBtn.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_connectBtn.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_connectBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_connectBtn.setCheckable(True)
        self.btn_connectBtn.setObjectName("btn_connectBtn")
        self.verticalLayout_4.addWidget(self.btn_connectBtn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.frame_connectionDropDown)
        self.line = QtWidgets.QFrame(self.frame_LeftSideBar)
        self.line.setMinimumSize(QtCore.QSize(0, 1))
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.frame_mainControls = QtWidgets.QFrame(self.frame_LeftSideBar)
        self.frame_mainControls.setMinimumSize(QtCore.QSize(0, 38))
        self.frame_mainControls.setMaximumSize(QtCore.QSize(16777215, 38))
        self.frame_mainControls.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_mainControls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mainControls.setLineWidth(0)
        self.frame_mainControls.setObjectName("frame_mainControls")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_mainControls)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_smallModeTogle = QtWidgets.QPushButton(self.frame_mainControls)
        self.btn_smallModeTogle.setMinimumSize(QtCore.QSize(58, 38))
        self.btn_smallModeTogle.setMaximumSize(QtCore.QSize(16777215, 38))
        self.btn_smallModeTogle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_smallModeTogle.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/arrow_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_smallModeTogle.setIcon(icon3)
        self.btn_smallModeTogle.setCheckable(True)
        self.btn_smallModeTogle.setObjectName("btn_smallModeTogle")
        self.horizontalLayout_3.addWidget(self.btn_smallModeTogle)
        self.btn_preferencesToggle = QtWidgets.QPushButton(self.frame_mainControls)
        self.btn_preferencesToggle.setMinimumSize(QtCore.QSize(58, 38))
        self.btn_preferencesToggle.setMaximumSize(QtCore.QSize(16777215, 38))
        self.btn_preferencesToggle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_preferencesToggle.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/preferences.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_preferencesToggle.setIcon(icon4)
        self.btn_preferencesToggle.setCheckable(False)
        self.btn_preferencesToggle.setObjectName("btn_preferencesToggle")
        self.horizontalLayout_3.addWidget(self.btn_preferencesToggle)
        self.btn_connectionDroDown = QtWidgets.QPushButton(self.frame_mainControls)
        self.btn_connectionDroDown.setMinimumSize(QtCore.QSize(58, 38))
        self.btn_connectionDroDown.setMaximumSize(QtCore.QSize(16777215, 38))
        self.btn_connectionDroDown.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_connectionDroDown.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/plug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_connectionDroDown.setIcon(icon5)
        self.btn_connectionDroDown.setCheckable(True)
        self.btn_connectionDroDown.setChecked(True)
        self.btn_connectionDroDown.setObjectName("btn_connectionDroDown")
        self.horizontalLayout_3.addWidget(self.btn_connectionDroDown)
        self.verticalLayout_3.addWidget(self.frame_mainControls)
        self.horizontalLayout_2.addWidget(self.frame_LeftSideBar)
        self.frame_dsahboardGraph = QtWidgets.QFrame(self.page_centralDashboard)
        self.frame_dsahboardGraph.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_dsahboardGraph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dsahboardGraph.setLineWidth(0)
        self.frame_dsahboardGraph.setObjectName("frame_dsahboardGraph")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_dsahboardGraph)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.splitter = QtWidgets.QSplitter(self.frame_dsahboardGraph)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(False)
        self.splitter.setHandleWidth(0)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layout_Graphs = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layout_Graphs.setContentsMargins(0, 0, 0, 1)
        self.layout_Graphs.setSpacing(4)
        self.layout_Graphs.setObjectName("layout_Graphs")
        self.frame_graphContainer = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_graphContainer.setMinimumSize(QtCore.QSize(0, 350))
        self.frame_graphContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_graphContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graphContainer.setObjectName("frame_graphContainer")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_graphContainer)
        self.verticalLayout_19.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.layout_graphContainer = QtWidgets.QGridLayout()
        self.layout_graphContainer.setSpacing(0)
        self.layout_graphContainer.setObjectName("layout_graphContainer")
        self.verticalLayout_19.addLayout(self.layout_graphContainer)
        self.layout_Graphs.addWidget(self.frame_graphContainer)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_terminalContainer = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_terminalContainer.setContentsMargins(0, 1, 0, 0)
        self.layout_terminalContainer.setSpacing(0)
        self.layout_terminalContainer.setObjectName("layout_terminalContainer")
        self.frame_terminalContainer = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_terminalContainer.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_terminalContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_terminalContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_terminalContainer.setObjectName("frame_terminalContainer")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_terminalContainer)
        self.verticalLayout_13.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_13.setSpacing(4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_terminalTextBrowserContainer = QtWidgets.QFrame(self.frame_terminalContainer)
        self.frame_terminalTextBrowserContainer.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_terminalTextBrowserContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_terminalTextBrowserContainer.setObjectName("frame_terminalTextBrowserContainer")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_terminalTextBrowserContainer)
        self.verticalLayout_20.setContentsMargins(1, 1, 3, 1)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.textBrowser_terminal = QtWidgets.QTextBrowser(self.frame_terminalTextBrowserContainer)
        self.textBrowser_terminal.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowser_terminal.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_terminal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_terminal.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.textBrowser_terminal.setOpenExternalLinks(True)
        self.textBrowser_terminal.setObjectName("textBrowser_terminal")
        self.verticalLayout_20.addWidget(self.textBrowser_terminal)
        self.verticalLayout_13.addWidget(self.frame_terminalTextBrowserContainer)
        self.frame_MessageSender = QtWidgets.QFrame(self.frame_terminalContainer)
        self.frame_MessageSender.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_MessageSender.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_MessageSender.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_MessageSender.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_MessageSender.setObjectName("frame_MessageSender")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_MessageSender)
        self.horizontalLayout_6.setContentsMargins(3, 0, 3, 0)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_clearTerminal = QtWidgets.QPushButton(self.frame_MessageSender)
        self.btn_clearTerminal.setMinimumSize(QtCore.QSize(40, 27))
        self.btn_clearTerminal.setMaximumSize(QtCore.QSize(47, 27))
        self.btn_clearTerminal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clearTerminal.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/bin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_clearTerminal.setIcon(icon6)
        self.btn_clearTerminal.setIconSize(QtCore.QSize(12, 12))
        self.btn_clearTerminal.setObjectName("btn_clearTerminal")
        self.horizontalLayout_6.addWidget(self.btn_clearTerminal)
        self.terminal_input = QtWidgets.QLineEdit(self.frame_MessageSender)
        self.terminal_input.setMinimumSize(QtCore.QSize(0, 35))
        self.terminal_input.setMaximumSize(QtCore.QSize(16777215, 35))
        self.terminal_input.setObjectName("terminal_input")
        self.horizontalLayout_6.addWidget(self.terminal_input)
        self.verticalLayout_13.addWidget(self.frame_MessageSender)
        self.layout_terminalContainer.addWidget(self.frame_terminalContainer)
        self.verticalLayout_15.addWidget(self.splitter)
        self.horizontalLayout_2.addWidget(self.frame_dsahboardGraph)
        self.stackedWidget_central.addWidget(self.page_centralDashboard)
        self.verticalLayout_2.addWidget(self.stackedWidget_central)
        self.statusBarFrame = QtWidgets.QFrame(self.centralFrame)
        self.statusBarFrame.setMinimumSize(QtCore.QSize(0, 17))
        self.statusBarFrame.setMaximumSize(QtCore.QSize(16777215, 17))
        self.statusBarFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusBarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusBarFrame.setLineWidth(0)
        self.statusBarFrame.setObjectName("statusBarFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.statusBarFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_statusBar = QtWidgets.QLabel(self.statusBarFrame)
        self.label_statusBar.setObjectName("label_statusBar")
        self.horizontalLayout.addWidget(self.label_statusBar)
        spacerItem4 = QtWidgets.QSpacerItem(933, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.statusBarFrame)
        self.verticalLayout.addWidget(self.centralFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_central.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_goBackHome.setText(_translate("MainWindow", "GO BACK"))
        self.btn_reloadWIndow.setText(_translate("MainWindow", "RELOAD WINDOW"))
        self.btn_launchRoomPanel.setText(_translate("MainWindow", "JOIN OR CREATE A SHARED ROOM"))
        self.btn_openDashboardEditor.setText(_translate("MainWindow", "OPEN DASHBOARD EDITOR"))
        self.label_longVersion.setText(_translate("MainWindow", "VERSION: COSMOS-v1.0.0-ALPHA"))
        self.btn_missionDisplay.setText(_translate("MainWindow", "NO MISSION ACTIVE"))
        self.btn_toggleRecordings.setText(_translate("MainWindow", " RECORDING"))
        self.btn_toggleCloudBackup.setText(_translate("MainWindow", "  CLOUD BACKUP"))
        self.label_state.setText(_translate("MainWindow", "N/A"))
        self.label_countdown.setText(_translate("MainWindow", "T- 00:00:00.0"))
        self.cb_bauds.setToolTip(_translate("MainWindow", "Baud Speed Option"))
        self.cb_bauds.setPlaceholderText(_translate("MainWindow", "N/A"))
        self.cb_ports.setToolTip(_translate("MainWindow", "Port Options"))
        self.cb_ports.setPlaceholderText(_translate("MainWindow", "N/A"))
        self.btn_toggleAutoReconnection.setToolTip(_translate("MainWindow", "Toggle Auto Reconnection"))
        self.btn_connectBtn.setToolTip(_translate("MainWindow", "Connect Via Serial"))
        self.btn_connectBtn.setText(_translate("MainWindow", "CONNECT"))
        self.btn_smallModeTogle.setToolTip(_translate("MainWindow", "Toggle Small Mode"))
        self.btn_preferencesToggle.setToolTip(_translate("MainWindow", "Go To Preferences"))
        self.btn_connectionDroDown.setToolTip(_translate("MainWindow", "Toggle The Connection Menu"))
        self.textBrowser_terminal.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Video Med\'; font-size:10pt; font-weight:504; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.terminal_input.setPlaceholderText(_translate("MainWindow", "Type here a message to send to the serial port"))
        self.label_statusBar.setText(_translate("MainWindow", "Version"))
from ..generated_files import src_rc
