#############################################################
#
#   .o88b.  .d88b.  .d8888. .88b  d88.  .d88b.  .d8888.
#  d8P  Y8 .8P  Y8. 88'  YP 88'YbdP`88 .8P  Y8. 88'  YP
#  8P      88    88 `8bo.   88  88  88 88    88 `8bo.
#  8b      88    88   `Y8b. 88  88  88 88    88   `Y8b.
#  Y8b  d8 `8b  d8' db   8D 88  88  88 `8b  d8' db   8D
#   `Y88P'  `Y88P'  `8888Y' YP  YP  YP  `Y88P'  `8888Y'
# 
# ★ StarLab RPL - COSMOS GROUND STATION ★
# Communications and Observation Station for Mission Operations and Surveillance
#
# By Martin Ortiz
# Version 1.0.0
# Date 06.08.2023
#
#############################################################
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/desing_files\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsForm(object):
    def setupUi(self, SettingsForm):
        SettingsForm.setObjectName("SettingsForm")
        SettingsForm.resize(1205, 70)
        SettingsForm.setMinimumSize(QtCore.QSize(0, 70))
        SettingsForm.setMaximumSize(QtCore.QSize(16777215, 70))
        SettingsForm.setStyleSheet("  selection-color: #ffffff;\n"
"  selection-background-color: #6357a3;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SettingsForm)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Config_1 = QtWidgets.QFrame(SettingsForm)
        self.Config_1.setMinimumSize(QtCore.QSize(0, 70))
        self.Config_1.setMaximumSize(QtCore.QSize(16777215, 70))
        self.Config_1.setStyleSheet("QFrame{\n"
"    font: 500 9.5pt \"Video Med\";\n"
"    border-radius: 4px;\n"
"    background-color: rgba(58, 59, 63, 0.2);\n"
"}\n"
"\n"
"QFrame:hover{\n"
"     background-color: rgba(68, 69, 73, 0.3);\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: none;\n"
"    border: none;\n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: none;\n"
"    border: none;\n"
"    margin-right: 10px;\n"
"}")
        self.Config_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Config_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Config_1.setObjectName("Config_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Config_1)
        self.horizontalLayout_2.setContentsMargins(25, 0, 25, 0)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name_desc = QtWidgets.QFrame(self.Config_1)
        self.name_desc.setStyleSheet("border: none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.name_desc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.name_desc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_desc.setObjectName("name_desc")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.name_desc)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.more_name_desc = QtWidgets.QFrame(self.name_desc)
        self.more_name_desc.setStyleSheet("border: none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.more_name_desc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.more_name_desc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.more_name_desc.setObjectName("more_name_desc")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.more_name_desc)
        self.verticalLayout.setContentsMargins(0, 9, 0, 9)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.profile = QtWidgets.QLabel(self.more_name_desc)
        self.profile.setMinimumSize(QtCore.QSize(65, 55))
        self.profile.setMaximumSize(QtCore.QSize(65, 55))
        self.profile.setStyleSheet("border-radius: 4px;\n"
"color: rgba(255, 255, 255, 0.45);\n"
"border: 1px solid rgba(200, 200, 200, 0.4);\n"
"background-color: rgba(0, 0, 0, 0.2);")
        self.profile.setAlignment(QtCore.Qt.AlignCenter)
        self.profile.setObjectName("profile")
        self.verticalLayout.addWidget(self.profile)
        self.horizontalLayout_4.addWidget(self.more_name_desc)
        self.frame = QtWidgets.QFrame(self.name_desc)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_config_name = QtWidgets.QLabel(self.frame)
        self.label_config_name.setStyleSheet("QLabel{\n"
"    font: 600 15pt \"Video SemBd\";\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    border:0;\n"
"    background: rgba(0,0,0,0);\n"
"}")
        self.label_config_name.setObjectName("label_config_name")
        self.verticalLayout_3.addWidget(self.label_config_name)
        self.description_label = QtWidgets.QLabel(self.frame)
        self.description_label.setMinimumSize(QtCore.QSize(400, 0))
        self.description_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.description_label.setStyleSheet("QLabel{\n"
"    \n"
"    \n"
"    font: 300 11pt \"Video Light\";\n"
"    color: rgba(255, 255, 255, 0.4);\n"
"    border:0;\n"
"    background: rgba(0,0,0,0);\n"
"}")
        self.description_label.setObjectName("description_label")
        self.verticalLayout_3.addWidget(self.description_label)
        self.horizontalLayout_4.addWidget(self.frame)
        self.horizontalLayout_2.addWidget(self.name_desc)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widgetcontainer = QtWidgets.QFrame(self.Config_1)
        self.widgetcontainer.setStyleSheet("QFrame{\n"
"    border: none;\n"
"    background-color: none;\n"
"    border-radius: none;}")
        self.widgetcontainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.widgetcontainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.widgetcontainer.setObjectName("widgetcontainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetcontainer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.string = QtWidgets.QLineEdit(self.widgetcontainer)
        self.string.setMinimumSize(QtCore.QSize(120, 33))
        self.string.setMaximumSize(QtCore.QSize(120, 33))
        self.string.setStyleSheet("QLineEdit{\n"
"    font: 600 10.5pt \"Video SemBd\";\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border-radius: 4px;\n"
"    color: rgba(255, 255, 255, 0.45); \n"
"    border: 1px solid rgba(0,0,0,0.4);\n"
"    background-color: rgba(0,0,0,0.2);\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgba(0,0,0,0.4);\n"
"}")
        self.string.setText("")
        self.string.setAlignment(QtCore.Qt.AlignCenter)
        self.string.setObjectName("string")
        self.horizontalLayout.addWidget(self.string)
        self.options = QtWidgets.QComboBox(self.widgetcontainer)
        self.options.setMinimumSize(QtCore.QSize(120, 33))
        self.options.setMaximumSize(QtCore.QSize(120, 33))
        self.options.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.options.setStyleSheet("QComboBox {\n"
"    font: 500 10.5pt \"Video Med\";\n"
"    padding-left: 8px;\n"
"    border-radius: 4px;\n"
"    color: rgba(255, 255, 255, 0.45);\n"
"    border: 1px solid rgba(0, 0, 0, 0.4);\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"    text-align: center;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: rgba(0, 0, 0, 0.4);\n"
"}\n"
"\n"
"QComboBox:drop-down {\n"
"    border: 0px;\n"
"    border-radius: 0px;\n"
"    font: 500 14.5pt \"Video Med\";\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/icons/down_arrow.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"QFrame {\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    background-color: rgba(52, 73, 94, 0.3);\n"
"    font: 500 14.5pt \"Video Med\";\n"
"    padding: 5px;\n"
"}\n"
"QComboBox QAbstractItem {\n"
"  padding: 4px 8px;\n"
"  border-radius: 4px;\n"
"  selection-background-color: none;\n"
"  border: none;\n"
"    border-bottom: 1px rgba(255,255,255,0.4);\n"
"    font: 500 14.5pt \"Video Med\";\n"
"}\n"
"QComboBox QAbstractItem::item {\n"
"  padding: 4px 8px;\n"
"  border-radius: 4px;\n"
"font: 500 14.5pt \"Video Med\";\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"  border: none;\n"
"  background-color: #6357a4;\n"
"font: 500 14.5pt \"Video Med\";\n"
"}\n"
"\n"
"QListView {\n"
"  border-radius: 4px;\n"
"  border: 1px solid #2b2d30;\n"
"  background-color: #12141a;\n"
"font: 500 14.5pt \"Video Med\";\n"
"  outline: none;\n"
"}")
        self.options.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.options.setObjectName("options")
        self.horizontalLayout.addWidget(self.options)
        self.misc = QtWidgets.QPushButton(self.widgetcontainer)
        self.misc.setMinimumSize(QtCore.QSize(120, 33))
        self.misc.setMaximumSize(QtCore.QSize(120, 33))
        self.misc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.misc.setStyleSheet("QPushButton {\n"
"    font: 500 10.5pt \"Video Med\";\n"
"    padding-left: 8px;\n"
"    border-radius: 4px;\n"
"    color: rgba(255, 255, 255, 0.45);\n"
"    border: 1px solid rgba(0, 0, 0, 0.4);\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.4);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.5);\n"
"}")
        self.misc.setObjectName("misc")
        self.horizontalLayout.addWidget(self.misc)
        self.toggle = QtWidgets.QFrame(self.widgetcontainer)
        self.toggle.setStyleSheet("\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.5);\n"
"}")
        self.toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toggle.setObjectName("toggle")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.toggle)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_on = QtWidgets.QPushButton(self.toggle)
        self.btn_on.setMinimumSize(QtCore.QSize(60, 33))
        self.btn_on.setMaximumSize(QtCore.QSize(60, 33))
        self.btn_on.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_on.setStyleSheet("QPushButton{\n"
"    padding: 1px 15px 1px 15px;\n"
"    font: 500 9.5pt \"Video Med\";\n"
"    border-radius: 4px;\n"
"    color: rgba(255, 255, 255, 0.45);\n"
"    border: 1px solid rgba(0, 0, 0, 0.4);\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-right: 0px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.4);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgba(186, 220, 88,0.5);\n"
"    border: 1px solid  rgba(106, 176, 76,0.8);\n"
"    border-right: 0px;\n"
"    color: rgba(255, 255, 255, 0.65);\n"
"    font: 500 10.5pt \"Video Med\";\n"
"}")
        self.btn_on.setCheckable(True)
        self.btn_on.setChecked(True)
        self.btn_on.setObjectName("btn_on")
        self.horizontalLayout_5.addWidget(self.btn_on)
        self.btn_off = QtWidgets.QPushButton(self.toggle)
        self.btn_off.setMinimumSize(QtCore.QSize(60, 33))
        self.btn_off.setMaximumSize(QtCore.QSize(60, 33))
        self.btn_off.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_off.setStyleSheet("QPushButton{\n"
"    padding: 1px 15px 1px 15px;\n"
"    color: rgba(255, 255, 255, 0.8);\n"
"     font: 500 9.5pt \"Video Med\";\n"
"    border-radius: 4px;\n"
"    color: rgba(255, 255, 255, 0.45);\n"
"    border: 1px solid rgba(0, 0, 0, 0.4);\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"\n"
"    border-left: 0px;\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.4);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border: 1px solid rgba(235, 77, 75,0.8);\n"
"    background-color: rgba(255, 121, 121,0.5);\n"
"    border-left: 0px;\n"
"    color: rgba(255, 255, 255, 0.65);\n"
"    font: 63 10.5pt \"Video SemBd\";\n"
"\n"
"}")
        self.btn_off.setCheckable(True)
        self.btn_off.setChecked(False)
        self.btn_off.setObjectName("btn_off")
        self.horizontalLayout_5.addWidget(self.btn_off)
        self.horizontalLayout.addWidget(self.toggle)
        self.integer = QtWidgets.QFrame(self.widgetcontainer)
        self.integer.setStyleSheet("QPushButton {\n"
"    font: 600 11.5pt \"Video SemBd\";\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    color: rgba(255, 255, 255, 0.45); \n"
"    border: 1px solid rgba(0,0,0,0.4);\n"
"   background-color: rgba(0,0,0,0.2);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0,0,0,0.4);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.5);\n"
"}")
        self.integer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.integer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.integer.setObjectName("integer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.integer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minus = QtWidgets.QPushButton(self.integer)
        self.minus.setMinimumSize(QtCore.QSize(40, 0))
        self.minus.setMaximumSize(QtCore.QSize(40, 33))
        self.minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minus.setStyleSheet("border-top-left-radius: 4px;\n"
"border-bottom-left-radius: 4px;\n"
"border-top-right-radius: 0;\n"
"border-bottom-right-radius: 0;")
        self.minus.setObjectName("minus")
        self.horizontalLayout_3.addWidget(self.minus)
        self.spinBox = QtWidgets.QSpinBox(self.integer)
        self.spinBox.setMinimumSize(QtCore.QSize(43, 33))
        self.spinBox.setMaximumSize(QtCore.QSize(43, 33))
        self.spinBox.setStyleSheet("QSpinBox{\n"
"    font: 600 10.5pt \"Video SemBd\";\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    color: rgba(255, 255, 255, 0.45); \n"
"    border: 1px solid rgba(0,0,0,0.4);\n"
"    border-left: 0px;\n"
"    border-right:0px; \n"
"   background-color: rgba(0,0,0,0.2);\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color: rgba(0,0,0,0.4);\n"
"}\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    width: 0;\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"")
        self.spinBox.setWrapping(False)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setReadOnly(False)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setAccelerated(True)
        self.spinBox.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.spinBox.setProperty("showGroupSeparator", True)
        self.spinBox.setSuffix("")
        self.spinBox.setMaximum(100000)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.plus = QtWidgets.QPushButton(self.integer)
        self.plus.setMinimumSize(QtCore.QSize(40, 0))
        self.plus.setMaximumSize(QtCore.QSize(40, 33))
        self.plus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plus.setStyleSheet("border-top-left-radius: 0;\n"
"border-bottom-left-radius: 0;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;")
        self.plus.setObjectName("plus")
        self.horizontalLayout_3.addWidget(self.plus)
        self.horizontalLayout.addWidget(self.integer)
        self.horizontalLayout_2.addWidget(self.widgetcontainer)
        self.verticalLayout_2.addWidget(self.Config_1)

        self.retranslateUi(SettingsForm)
        self.plus.clicked.connect(self.spinBox.stepUp) # type: ignore
        self.btn_on.clicked.connect(self.btn_off.toggle) # type: ignore
        self.btn_off.clicked.connect(self.btn_on.toggle) # type: ignore
        self.minus.clicked['bool'].connect(self.spinBox.stepDown) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingsForm)

    def retranslateUi(self, SettingsForm):
        _translate = QtCore.QCoreApplication.translate
        SettingsForm.setWindowTitle(_translate("SettingsForm", "Form"))
        self.profile.setText(_translate("SettingsForm", "?"))
        self.label_config_name.setText(_translate("SettingsForm", "NAME"))
        self.description_label.setText(_translate("SettingsForm", "Description"))
        self.misc.setText(_translate("SettingsForm", "OPEN"))
        self.btn_on.setText(_translate("SettingsForm", "ON"))
        self.btn_off.setText(_translate("SettingsForm", "OFF"))
        self.minus.setText(_translate("SettingsForm", "-"))
        self.plus.setText(_translate("SettingsForm", "+"))
from ..generated_files import src_rc
