######################### Xnxe9 <3? #########################
#
#   .o88b.  .d88b.  .d8888. .88b  d88.  .d88b.  .d8888.
#  d8P  Y8 .8P  Y8. 88'  YP 88'YbdP`88 .8P  Y8. 88'  YP
#  8P      88    88 `8bo.   88  88  88 88    88 `8bo.
#  8b      88    88   `Y8b. 88  88  88 88    88   `Y8b.
#  Y8b  d8 `8b  d8' db   8D 88  88  88 `8b  d8' db   8D
#   `Y88P'  `Y88P'  `8888Y' YP  YP  YP  `Y88P'  `8888Y'
# 
# ★ StarLab RPL - COSMOS GROUND STATION ★
# Communications and Observation Station for Mission Operations and Surveillance
#
# By Martin Ortiz
# Version 1.0.0
# Date 06.08.2023
#
#############################################################

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/desing_files\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsForm(object):
    def setupUi(self, SettingsForm):
        SettingsForm.setObjectName("SettingsForm")
        SettingsForm.resize(880, 75)
        SettingsForm.setMinimumSize(QtCore.QSize(0, 75))
        SettingsForm.setMaximumSize(QtCore.QSize(16777215, 85))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SettingsForm)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Config_1 = QtWidgets.QFrame(SettingsForm)
        self.Config_1.setMinimumSize(QtCore.QSize(0, 75))
        self.Config_1.setMaximumSize(QtCore.QSize(16777215, 75))
        self.Config_1.setStyleSheet("QFrame{\n"
"    font: 500 9pt \"Video Med\";\n"
"    border-radius: 6px;\n"
"    border: 1px solid rgba(10,12,16,0.2);\n"
"    background-color: rgba(52, 73, 94, 0.2);\n"
"}\n"
"\n"
"\n"
"QFrame:hover{\n"
"     background-color: rgba(52, 73, 94, 0.3);\n"
"}\n"
"")
        self.Config_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Config_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Config_1.setObjectName("Config_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Config_1)
        self.horizontalLayout_2.setContentsMargins(25, -1, 25, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.Config_1)
        self.frame.setStyleSheet("border: none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_config_name = QtWidgets.QLabel(self.frame)
        self.label_config_name.setStyleSheet("QLabel{\n"
"    font: 600 15pt \"Video SemBd\";\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    border:0;\n"
"    background: rgba(0,0,0,0);\n"
"}")
        self.label_config_name.setObjectName("label_config_name")
        self.verticalLayout.addWidget(self.label_config_name)
        self.description_label = QtWidgets.QLabel(self.frame)
        self.description_label.setMinimumSize(QtCore.QSize(400, 0))
        self.description_label.setMaximumSize(QtCore.QSize(400, 16777215))
        self.description_label.setStyleSheet("QLabel{\n"
"    \n"
"    \n"
"    font: 300 10pt \"Video Light\";\n"
"    color: rgba(255, 255, 255, 0.4);\n"
"    border:0;\n"
"    background: rgba(0,0,0,0);\n"
"}")
        self.description_label.setObjectName("description_label")
        self.verticalLayout.addWidget(self.description_label)
        self.horizontalLayout_2.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(629, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.Config_1)
        self.frame_2.setStyleSheet("QFrame{\n"
"    border: none;\n"
"    background-color: none;\n"
"    border-radius: none;}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(88, 33))
        self.lineEdit.setMaximumSize(QtCore.QSize(88, 33))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    font: 600 9.5pt \"Video SemBd\";\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border-radius: 5px;\n"
"    color: rgba(255, 255, 255, 0.45); \n"
"    border: 1px solid rgba(0,0,0,0.4);\n"
"    background-color: rgba(0,0,0,0.2);\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgba(0,0,0,0.4);\n"
"}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.options_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.options_comboBox.setMinimumSize(QtCore.QSize(88, 33))
        self.options_comboBox.setMaximumSize(QtCore.QSize(88, 33))
        self.options_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.options_comboBox.setStyleSheet("QComboBox {\n"
"    font: 500 9pt \"Video Med\";\n"
"    padding-left: 5px;\n"
"    border-radius: 4px;\n"
"    color: rgba(255, 255, 255, 0.45);\n"
"    border: 1px solid rgba(0, 0, 0, 0.4);\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"    text-align: center;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: rgba(0, 0, 0, 0.4);\n"
"}\n"
"\n"
"QComboBox:drop-down {\n"
"    border: 0px;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QFrame{\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    background-color: rgba(52, 73, 94, 0.3);\n"
"    font: 500 10.5pt \"Video Med\";\n"
"}\n"
"")
        self.options_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.options_comboBox.setObjectName("options_comboBox")
        self.horizontalLayout.addWidget(self.options_comboBox)
        self.checkeable = QtWidgets.QPushButton(self.frame_2)
        self.checkeable.setMinimumSize(QtCore.QSize(88, 33))
        self.checkeable.setMaximumSize(QtCore.QSize(188, 33))
        self.checkeable.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkeable.setStyleSheet("QPushButton{\n"
"    padding: 1px 15px 1px 15px;\n"
"    color: rgba(255, 255, 255, 0.8);\n"
"    font: 500 9pt \"Video Med\";\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(255, 85, 127,0.6);\n"
"    background-color: rgba(255, 85, 127,0.2);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 85, 127,0.4);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgba(156, 255, 136, 0.5);\n"
"    border: 1px solid rgba(156, 255, 136,0.8);\n"
"}")
        self.checkeable.setCheckable(False)
        self.checkeable.setChecked(False)
        self.checkeable.setObjectName("checkeable")
        self.horizontalLayout.addWidget(self.checkeable)
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setMinimumSize(QtCore.QSize(88, 33))
        self.spinBox.setMaximumSize(QtCore.QSize(88, 33))
        self.spinBox.setStyleSheet("QSpinBox{\n"
"    font: 600 9.5pt \"Video SemBd\";\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border-radius: 5px;\n"
"    color: rgba(255, 255, 255, 0.45); \n"
"    border: 1px solid rgba(0,0,0,0.4);\n"
"    background-color: rgba(0,0,0,0.2);\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color: rgba(0,0,0,0.4);\n"
"}")
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox.setAccelerated(True)
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setSuffix("")
        self.spinBox.setMaximum(100000)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.Config_1)

        self.retranslateUi(SettingsForm)
        QtCore.QMetaObject.connectSlotsByName(SettingsForm)

    def retranslateUi(self, SettingsForm):
        _translate = QtCore.QCoreApplication.translate
        SettingsForm.setWindowTitle(_translate("SettingsForm", "Form"))
        self.label_config_name.setText(_translate("SettingsForm", "NAME"))
        self.description_label.setText(_translate("SettingsForm", "Description"))
        self.checkeable.setText(_translate("SettingsForm", "DISABLED"))
