#############################################################
#
#   .o88b.  .d88b.  .d8888. .88b  d88.  .d88b.  .d8888.
#  d8P  Y8 .8P  Y8. 88'  YP 88'YbdP`88 .8P  Y8. 88'  YP
#  8P      88    88 `8bo.   88  88  88 88    88 `8bo.
#  8b      88    88   `Y8b. 88  88  88 88    88   `Y8b.
#  Y8b  d8 `8b  d8' db   8D 88  88  88 `8b  d8' db   8D
#   `Y88P'  `Y88P'  `8888Y' YP  YP  YP  `Y88P'  `8888Y'
# 
# ★ StarLab RPL - COSMOS GROUND STATION ★
# Communications and Observation Station for Mission Operations and Surveillance
#
# By Martin Ortiz
# Version 1.0.0
# Date 06.08.2023
#
#############################################################
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lowgo\Desktop\Desktop\1. DEV\1. STARLAB\cosmos\cosmos-ground-station\src\ui\desing_files\missions.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MissionForm(object):
    def setupUi(self, MissionForm):
        MissionForm.setObjectName("MissionForm")
        MissionForm.resize(360, 50)
        MissionForm.setMinimumSize(QtCore.QSize(0, 50))
        MissionForm.setMaximumSize(QtCore.QSize(16777215, 50))
        MissionForm.setStyleSheet("  selection-color: #ffffff;\n"
"  selection-background-color: #6357a3;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MissionForm)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(MissionForm)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setStyleSheet("QFrame{\n"
"    font: 500 9.5pt \"Video Med\";\n"
"    border-radius: 4px;\n"
"    background-color: rgba(58, 59, 63, 0.2);\n"
"}\n"
"\n"
"QFrame:hover{\n"
"     background-color: rgba(68, 69, 73, 0.3);\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: none;\n"
"    border: none;\n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: none;\n"
"    border: none;\n"
"    margin-right: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.frame)
        self.titleLabel.setStyleSheet("QLabel{\n"
"    \n"
"    \n"
"    font: 300 11pt \"Video Light\";\n"
"    color: rgba(255, 255, 255, 0.4);\n"
"    border:0;\n"
"    background: rgba(0,0,0,0);\n"
"}")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.descripTionLabel = QtWidgets.QLabel(self.frame)
        self.descripTionLabel.setStyleSheet("QLabel{\n"
"    \n"
"    \n"
"    font: 300 8.5pt \"Video Light\";\n"
"    color: rgba(255, 255, 255, 0.4);\n"
"    border:0;\n"
"    background: rgba(0,0,0,0);\n"
"}")
        self.descripTionLabel.setObjectName("descripTionLabel")
        self.verticalLayout.addWidget(self.descripTionLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(MissionForm)
        QtCore.QMetaObject.connectSlotsByName(MissionForm)

    def retranslateUi(self, MissionForm):
        _translate = QtCore.QCoreApplication.translate
        MissionForm.setWindowTitle(_translate("MissionForm", "Form"))
        self.titleLabel.setText(_translate("MissionForm", "TextLabel"))
        self.descripTionLabel.setText(_translate("MissionForm", "TextLabel"))
import src_rc
